'use server';

/**
 * @fileOverview Generates a dynamic Scrum-themed story based on player decisions and dice rolls.
 *
 * - generateScrumStory - A function that generates the Scrum story.
 * - GenerateScrumStoryInput - The input type for the generateScrumStory function.
 * - GenerateScrumStoryOutput - The return type for the generateScrumStory function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateScrumStoryInputSchema = z.object({
  previousStory: z.string().describe('The previous story generated by the AI.'),
  playerDecision: z.string().describe('The player decision.'),
  diceRollResult: z.number().describe('The result of the dice roll.'),
});
export type GenerateScrumStoryInput = z.infer<typeof GenerateScrumStoryInputSchema>;

const GenerateScrumStoryOutputSchema = z.object({
  newStory: z.string().describe('The new story generated by the AI, followed by three options for the player, each on a new line and starting with a hyphen. Example: "Story...\n- Option 1\n- Option 2\n- Option 3"'),
});
export type GenerateScrumStoryOutput = z.infer<typeof GenerateScrumStoryOutputSchema>;

export async function generateScrumStory(input: GenerateScrumStoryInput): Promise<GenerateScrumStoryOutput> {
  return generateScrumStoryFlow(input);
}

const generateScrumStoryPrompt = ai.definePrompt({
  name: 'generateScrumStoryPrompt',
  input: {schema: GenerateScrumStoryInputSchema},
  output: {schema: GenerateScrumStoryOutputSchema},
  prompt: `Eres un maestro de mazmorras experto en Scrum, narrando una historia en español. 
Basándote en la historia anterior, la decisión del jugador y el resultado del dado, genera el siguiente capítulo de la historia.

Historia anterior:
{{previousStory}}

Decisión del jugador:
{{playerDecision}}

Resultado del dado:
{{diceRollResult}}

Genera un nuevo capítulo de la historia en español que continúe la narrativa de forma coherente y atractiva. La historia debe tener un máximo de 100 palabras.
MUY IMPORTANTE: Después del párrafo de la historia, proporciona SIEMPRE tres opciones para que el jugador elija. Cada opción debe estar en una nueva línea y comenzar con un guion (-).`,
});

const generateScrumStoryFlow = ai.defineFlow(
  {
    name: 'generateScrumStoryFlow',
    inputSchema: GenerateScrumStoryInputSchema,
    outputSchema: GenerateScrumStoryOutputSchema,
  },
  async input => {
    const {output} = await generateScrumStoryPrompt(input);
    return output!;
  }
);
